name: java and maven based

run-name: java-maven

on: 
 push
jobs:
  jave_maven:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup Java JDK
       uses: actions/setup-java@v4.6.0
       with:
        distribution: "zulu"
        java-version: "17"
         
